In [3]:
import numpy as np
# Create a matrix
A = np.array([[1, 2], [3, 4]])
# Inverse of a matrix
A_inv = np.linalg.inv(A)
# Matrix multiplication
B = np.array([[5], [6]])
result = np.dot(A_inv, B)

print("Result:", result)


Result: [[-4. ]
 [ 4.5]]


In [2]:
from scipy.linalg import solve

# Create a matrix
A = np.array([[1, 2], [3, 4]])

# Solve a linear system of equations
B = np.array([5, 6])
result = solve(A, B)

print("Result:", result)


Result: [-4.   4.5]


In [4]:
import numpy as np

A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print(x)
A_inv = np.linalg.inv(A)

x = np.dot(A_inv, y)
print(x)
from scipy.linalg import lu

P, L, U = lu(A)
print('P:\n', P)
print('L:\n', L)
print('U:\n', U)
print('LU:\n',np.dot(L, U))
print(np.dot(P, A))

[ 2.20833333 -2.58333333 -0.18333333]
[ 2.20833333 -2.58333333 -0.18333333]
P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
U:
 [[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]
LU:
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]
[[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]


In [14]:
import numpy as np

def gaussian_elimination(A, B):
    n = len(A)
    # Augment the matrix
    augmented = np.concatenate((A, B.reshape(-1, 1)), axis=1)
    
    for i in range(n):
        # Pivot for the current column
        pivot = augmented[i, i]
        # Elimination step
        for j in range(i+1, n):
            ratio = augmented[j, i] / pivot
            augmented[j] =augmented[j]- ratio * augmented[i]
    
    # Back substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (augmented[i, -1] - np.dot(augmented[i, :-1], x)) / augmented[i, i]
    
    return x

# Example usage
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])
B = np.array([8, -11, -3])
solution = gaussian_elimination(A, B)
print("Solution:", solution)


Solution: [-inf  inf   1.]


C:\Users\kotap\AppData\Local\Temp\ipykernel_19004\1555840458.py:13: RuntimeWarning: divide by zero encountered in scalar divide
  ratio = augmented[j, i] / pivot
C:\Users\kotap\AppData\Local\Temp\ipykernel_19004\1555840458.py:14: RuntimeWarning: invalid value encountered in multiply
  augmented[j] =augmented[j]- ratio * augmented[i]
C:\Users\kotap\AppData\Local\Temp\ipykernel_19004\1555840458.py:14: RuntimeWarning: invalid value encountered in cast
  augmented[j] =augmented[j]- ratio * augmented[i]
C:\Users\kotap\AppData\Local\Temp\ipykernel_19004\1555840458.py:19: RuntimeWarning: divide by zero encountered in scalar divide
  x[i] = (augmented[i, -1] - np.dot(augmented[i, :-1], x)) / augmented[i, i]


In [15]:
from scipy.linalg import lu_factor, lu_solve

# Example usage
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])
B = np.array([8, -11, -3])

# LU decomposition
LU, piv = lu_factor(A)
solution = lu_solve((LU, piv), B)
print("Solution:", solution)

Solution: [ 2.  3. -1.]


In [16]:
from numpy.linalg import eig

# Example usage
A = np.array([[2, -1],
              [-1, 3]])

eigenvalues, eigenvectors = eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [1.38196601 3.61803399]
Eigenvectors: [[-0.85065081  0.52573111]
 [-0.52573111 -0.85065081]]


In [7]:
import numpy as np

# Define a matrix
A = np.array([[1, 2], [3, 4]])

# Calculate the inverse of the matrix
A_inv = np.linalg.inv(A)

print("Original matrix:")
print(A)
print("\nInverse matrix:")
print(A_inv)

Original matrix:
[[1 2]
 [3 4]]

Inverse matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [21]:
import numpy as np

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
C = np.dot(A, B)  # Alternatively, you can use np.matmul(A, B)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nResult:")
print(C)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Result:
[[19 22]
 [43 50]]


In [9]:
import numpy as np

# Define a matrix
A = np.array([[2, -1], [-1, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
for i in range(len(eigenvalues)):
    print("Eigenvalue:", eigenvalues[i])
    print("Eigenvector:", eigenvectors[:, i])
    print()

Eigenvalues: [1.38196601 3.61803399]
Eigenvectors:
Eigenvalue: 1.381966011250105
Eigenvector: [-0.85065081 -0.52573111]

Eigenvalue: 3.618033988749895
Eigenvector: [ 0.52573111 -0.85065081]



In [25]:
# importing numpy for matrix operations 
import numpy 
x = numpy.array([[1, 2], [4, 5]]) 
y = numpy.array([[7, 8], [9, 10]]) 
print ("addition :")
print(numpy.add(x,y)) 
print ("subtraction:") 
print (numpy.subtract(x,y)) 
print ("division:") 
print (numpy.divide(x,y)) 
print ("multiplication : ") 
print (numpy.multiply(x,y))    
print (" product:") 
print (numpy.dot(x,y)) 

addition :
[[ 8 10]
 [13 15]]
subtraction:
[[-6 -6]
 [-5 -5]]
division:
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
multiplication : 
[[ 7 16]
 [36 50]]
 product:
[[25 28]
 [73 82]]
