In [1]:
import numpy as np

# Generate a random matrix
A = np.random.randn(5, 3)

# Perform Singular Value Decomposition (SVD)
U, S, Vt = np.linalg.svd(A)

print("Original matrix:")
print(A)
print("\nLeft singular vectors (U):")
print(U)
print("\nSingular values:")
print(S)
print("\nRight singular vectors (V^T):")
print(Vt)

Original matrix:
[[ 0.90971974 -0.15761055 -1.60681888]
 [-0.64123     0.90117189 -1.34341184]
 [ 0.35110955 -0.14705473 -0.05305208]
 [ 0.36462802 -1.01055907  0.38835173]
 [ 0.97548954  0.13729756  0.34106153]]

Left singular vectors (U):
[[ 0.58143824 -0.74225249 -0.13849024 -0.29920199  0.04784811]
 [ 0.72077993  0.33088152  0.00824163  0.59604334  0.12513244]
 [-0.01836377 -0.21816709  0.0529912   0.33468137 -0.91501159]
 [-0.34394441 -0.3755809  -0.57903318  0.57505865  0.27325693]
 [-0.15417806 -0.38848523  0.80166392  0.3354198   0.26483367]]

Singular values:
[2.27858301 1.73785371 0.88867053]

Right singular vectors (V^T):
[[-0.09457563  0.38928324 -0.91624997]
 [-0.85158148  0.44506569  0.2769937 ]
 [ 0.51562043  0.80645837  0.28941403]]


In [3]:
import numpy as np

# Define a sample matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Perform SVD
U, S, VT = np.linalg.svd(A)

# U, S, and VT contain the left singular vectors, singular values, and right singular vectors respectively

print("Left Singular Vectors (U):")
print(U)
print()

print("Singular Values (S):")
print(np.diag(S))  # Display as a diagonal matrix
print()

print("Right Singular Vectors (VT):")
print(VT)


Left Singular Vectors (U):
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]

Singular Values (S):
[[1.68481034e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06836951e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.33475287e-16]]

Right Singular Vectors (VT):
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [5]:
import numpy as np
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Target

# Perform Singular Value Decomposition
U, S, VT = np.linalg.svd(X)

# U, S, and VT contain the left singular vectors, singular values, and right singular vectors respectively

print("Left Singular Vectors (U):")
print(U)
print()

print("Singular Values (S):")
print(np.diag(S))  # Display as a diagonal matrix
print()

print("Right Singular Vectors (VT):")
print(VT)

Left Singular Vectors (U):
[[-0.06161685  0.12961144  0.0021386  ... -0.09343429 -0.09573864
  -0.08085465]
 [-0.05807094  0.11101978  0.07067239 ...  0.03690405 -0.03153954
   0.01309526]
 [-0.05676305  0.11796647  0.00434255 ...  0.03066199  0.19531473
   0.13569909]
 ...
 [-0.0940593  -0.0498297  -0.04144001 ...  0.98181631 -0.02194514
  -0.00894446]
 [-0.09488961 -0.05610123 -0.21297821 ... -0.02155617  0.94178018
  -0.02971961]
 [-0.08847836 -0.0515697  -0.09575285 ... -0.0086052  -0.03021088
   0.9736599 ]]

Singular Values (S):
[[95.95991387  0.          0.          0.        ]
 [ 0.         17.76103366  0.          0.        ]
 [ 0.          0.          3.46093093  0.        ]
 [ 0.          0.          0.          1.88482631]]

Right Singular Vectors (VT):
[[-0.75110816 -0.38008617 -0.51300886 -0.16790754]
 [ 0.2841749   0.5467445  -0.70866455 -0.34367081]
 [ 0.50215472 -0.67524332 -0.05916621 -0.53701625]
 [ 0.32081425 -0.31725607 -0.48074507  0.75187165]]


In [6]:
import numpy as np

# Generate a random symmetric matrix (for demonstration)
n = 4
A = np.random.rand(n, n)
A = np.dot(A, A.transpose())  # Ensure A is symmetric

# Perform eigenvalue decomposition
eigenvalues, eigenvectors = np.linalg.eig(A)

# Sort eigenvalues and eigenvectors in descending order
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)


Eigenvalues: [2.72139724 0.20384009 0.02798485 0.02081227]
Eigenvectors: [[ 0.6418165   0.08701349 -0.74324018 -0.16761342]
 [ 0.3981236  -0.79997348  0.3209327  -0.31391437]
 [ 0.48063203  0.59168457  0.55819403 -0.32759984]
 [ 0.44560299 -0.04878989  0.18170212  0.87523817]]


In [7]:
import numpy as np

# Define a square matrix
A = np.array([[2, -1], [-1, 3]])

# Perform eigenvalue decomposition
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
for i in range(len(eigenvalues)):
    print("Eigenvalue:", eigenvalues[i])
    print("Eigenvector:", eigenvectors[:, i])
    print()

Eigenvalues: [1.38196601 3.61803399]
Eigenvectors:
Eigenvalue: 1.381966011250105
Eigenvector: [-0.85065081 -0.52573111]

Eigenvalue: 3.618033988749895
Eigenvector: [ 0.52573111 -0.85065081]



In [9]:
import numpy as np

# Define a square matrix
A = np.array([[2, -1], [-1, 3]])

# Perform eigenvalue decomposition
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:",eigenvalues)
print("Eigenvectors:",eigenvectors)

Eigenvalues: [1.38196601 3.61803399]
Eigenvectors: [[-0.85065081  0.52573111]
 [-0.52573111 -0.85065081]]
