In [2]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf
x=tf.constant(4.0)
x-tf.constant(4,shape=(1,1),dtype=tf.float32)
y=tf.constant([[1,2,3],[4,5,6]])
print(y.shape)
x=tf.ones((3,3))
print(x)
x=tf.zeros((2,3)) #create matrix with all zeros
print(x)
x=tf.eye(3) #Identity matrix
print(x)

(2, 3)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [3]:
x=tf.random.normal((3,3),mean=0,stddev=1)
print(x)

tf.Tensor(
[[-1.5577892  -1.1007742   2.3631928 ]
 [-1.9811978  -0.53216964  0.3814689 ]
 [-0.17885514  0.57675385 -0.5973122 ]], shape=(3, 3), dtype=float32)


In [4]:
x=tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [5]:
x=tf.range(start=1,limit=10,delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [6]:
x=4.5
y=tf.cast(x,dtype=tf.float64)
print(y)

tf.Tensor(4.5, shape=(), dtype=float64)


In [7]:
#mathematical operations

In [8]:
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
z=tf.add(x,y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [9]:
z1=tf.subtract(x,y)
print(z1)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [10]:
z2=tf.divide(x,y)
print(z2)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [11]:
z3=tf.tensordot(x,y,axes=1)
print(z3)

tf.Tensor(46, shape=(), dtype=int32)


In [12]:
#matrix multiplication
x1=tf.random.normal((2,3))
x2=tf.random.normal((3,4))
print(x1)
print(x2)
z4=tf.matmul(x1,x2)
print(z4)

tf.Tensor(
[[ 1.6956962   0.2409151   0.92257744]
 [ 0.08149326 -1.2125518   2.288515  ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-0.529961   -1.219475   -0.00287996 -0.2536661 ]
 [-0.25023597 -1.7429425   0.44790742  0.85308015]
 [-1.8667113  -0.01719397  0.61115646  0.64613956]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[-2.6811242  -2.503623    0.66686326  0.37149304]
 [-4.011761    1.9746804   0.85529506  0.42362416]], shape=(2, 4), dtype=float32)


In [13]:
a=tf.constant([0,1,1,2,3,5,8,13,21,34])
print(a.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


In [14]:
print("First:",a[0].numpy())
print("Second:",a[1].numpy())
print("Last:",a[-1].numpy())
print("Everything:",a[:].numpy())
print("Before 4:",a[:4].numpy())
print("From 4 to the end:",a[4:].numpy())
print("From 2,before 7:",a[2:7].numpy())
print("Every other item:",a[::2].numpy())
print("Reversed:",a[::-1].numpy())


First: 0
Second: 1
Last: 34
Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2,before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


In [15]:
b=tf.constant([[1, 2],
               [3, 4],
               [5, 6]], dtype=tf.float16)

print(b.numpy())


[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [16]:
print(b[1, 1].numpy())


4.0


In [17]:
print("Second row:",b[1, :].numpy())
print("Second column:",b[:, 1].numpy())
print("Last row:",b[-1, :].numpy())
print("First item in last column:",b[0, -1].numpy())
print("Skip the first row:")
print(b[1:, :].numpy(), "\n")

Second row: [3. 4.]
Second column: [2. 4. 6.]
Last row: [5. 6.]
First item in last column: 2.0
Skip the first row:
[[3. 4.]
 [5. 6.]] 



In [18]:
x=tf.constant([[1],[2],[3]])
print(x.shape)
print(x.shape.as_list())

(3, 1)
[3, 1]


In [19]:
x = tf.constant([1, 2, 3])
y = tf.constant(2)
z = tf.constant([2, 2, 2])
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [20]:
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [21]:
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


In [22]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [23]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)
print(ragged_tensor.shape)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>
(4, None)


In [24]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")
print(tf.sparse.to_dense(sparse_tensor))


SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
